services:
  supanova-server:
    image: jdgarner/supanova-server:latest
    container_name: supanova-server
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    env_file: .env
    # network_mode host needed so it can connect to postgres running outside of docker
    # once we move postgres to run inside docker, we can remove this
    network_mode: host
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:${SERVER_PORT}/health || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s
    logging:
      driver: fluentd
      options:
        fluentd-address: "localhost:24224"
        tag: "{{.Name}}"
        fluentd-async: "true"
        fluentd-max-retries: "5"
